name: logic_networks
description: A multiplayer logic game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  image_picker  : ^0.8.5+3
  firebase_storage: ^12.1.3
  provider: ^6.1.2
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.3.2
  flutter_facebook_auth: ^7.0.1
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  fhir_auth: ^0.11.0-dev.1
  animated_text_kit: ^4.2.2
  flutter_hooks: ^0.18.0
  google_fonts: ^4.0.4
  lottie: ^3.1.2
  flutter_animated_button: ^2.0.3
  glassmorphism: ^3.0.0
  flutter_form_builder: ^9.4.1
  intl: ^0.19.0
  flutter_markdown: ^0.7.3+1
  flutter_quill: ^10.4.3
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  assets:
    - assets/defaultpp.png
    - assets/icon.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: MyFlutterApp.ttf
   