// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtCGW8quUVeer_ImQURcYaJyzm8zzDG0M',
    appId: '1:366229891129:web:c6ffb574c4bdf4a3ee45e8',
    messagingSenderId: '366229891129',
    projectId: 'hosting-cb11e',
    authDomain: 'hosting-cb11e.firebaseapp.com',
    databaseURL: 'https://hosting-cb11e-default-rtdb.firebaseio.com',
    storageBucket: 'hosting-cb11e.appspot.com',
    measurementId: 'G-MKKNTWSDJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCxyVP4oA7ltvfhV8hX5zMfzajJRM9nkY',
    appId: '1:366229891129:android:b1f97b2dd901b336ee45e8',
    messagingSenderId: '366229891129',
    projectId: 'hosting-cb11e',
    databaseURL: 'https://hosting-cb11e-default-rtdb.firebaseio.com',
    storageBucket: 'hosting-cb11e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr6FdM-R9S0DlEjoSYXJW1bG1mxNWAys4',
    appId: '1:366229891129:ios:d19dc29797d0eb48ee45e8',
    messagingSenderId: '366229891129',
    projectId: 'hosting-cb11e',
    databaseURL: 'https://hosting-cb11e-default-rtdb.firebaseio.com',
    storageBucket: 'hosting-cb11e.appspot.com',
    iosClientId: '366229891129-ktdt9ad7bfca8rlkjrdo4a5greuic9s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.system',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr6FdM-R9S0DlEjoSYXJW1bG1mxNWAys4',
    appId: '1:366229891129:ios:d19dc29797d0eb48ee45e8',
    messagingSenderId: '366229891129',
    projectId: 'hosting-cb11e',
    databaseURL: 'https://hosting-cb11e-default-rtdb.firebaseio.com',
    storageBucket: 'hosting-cb11e.appspot.com',
    iosClientId: '366229891129-ktdt9ad7bfca8rlkjrdo4a5greuic9s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.system',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtCGW8quUVeer_ImQURcYaJyzm8zzDG0M',
    appId: '1:366229891129:web:38037495aa04594cee45e8',
    messagingSenderId: '366229891129',
    projectId: 'hosting-cb11e',
    authDomain: 'hosting-cb11e.firebaseapp.com',
    databaseURL: 'https://hosting-cb11e-default-rtdb.firebaseio.com',
    storageBucket: 'hosting-cb11e.appspot.com',
    measurementId: 'G-38EKT2TNVF',
  );
}
